# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin_all_from "app/javascript/custom",      under: "custom"
pin "jquery", to: "https://ga.jspm.io/npm:jquery@3.6.0/dist/jquery.js"
pin "jquery-ui-dist", to: "https://ga.jspm.io/npm:jquery-ui-dist@1.13.1/jquery-ui.js"
pin "trix"
pin "@rails/actiontext", to: "actiontext.js"
pin "@editorjs/editorjs", to: "https://cdn.jsdelivr.net/npm/@editorjs/editorjs@2.29.0/dist/editorjs.umd.min.js"
pin "@editorjs/header", to: "https://cdn.jsdelivr.net/npm/@editorjs/header@2.8.1/dist/header.umd.js"
pin "@editorjs/link", to: "https://cdn.jsdelivr.net/npm/@editorjs/link@2.6.2/dist/link.umd.js"
pin "@editorjs/raw", to: "https://cdn.jsdelivr.net/npm/@editorjs/raw@2.5.0/dist/raw.umd.js"
pin "@editorjs/simple-image", to: "https://cdn.jsdelivr.net/npm/@editorjs/simple-image@1.6.0/dist/simple-image.umd.js"
pin "@editorjs/image", to: "https://cdn.jsdelivr.net/npm/@editorjs/image@2.9.0/dist/image.umd.js"
pin "@editorjs/checklist", to: "https://cdn.jsdelivr.net/npm/@editorjs/checklist@1.6.0/dist/checklist.umd.js"
pin "@editorjs/list", to: "https://cdn.jsdelivr.net/npm/@editorjs/list@1.9.0/dist/list.umd.js"
pin "@editorjs/embed", to: "https://cdn.jsdelivr.net/npm/@editorjs/embed@2.7.0/dist/embed.umd.js"
pin "@editorjs/quote", to: "https://cdn.jsdelivr.net/npm/@editorjs/quote@2.6.0/dist/quote.umd.min.js"
pin "editorjs-html", to: "https://cdn.jsdelivr.net/npm/editorjs-html@3.4.0/build/edjsHTML.js"
pin "editorjs-text-color-plugin", to: "https://cdn.jsdelivr.net/npm/editorjs-text-color-plugin@2.0.3/dist/bundle.js"